# permissions for end users to view pads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pad-viewer-role
rules:
- apiGroups:
  - indicator.padoperator
  resources:
  - pads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - indicator.padoperator
  resources:
  - pads/status
  verbs:
  - get
