apiVersion: indicator.padoperator/v1alpha1
kind: Pad
metadata:
  name: pad-sample
spec:
   replicas: 1
   source: "http://demo.robustperception.io:9090/"
   metrics: "up"
   retraining_interval: "10"
